Repository pinellolab/pyrovelocity, pull requests merged in 2022-11, with the labels that each got.

#19 add IaC development environment
  conda/README.md
  reproducibility/environment/.gitignore
  reproducibility/environment/.terraform.lock.hcl
  reproducibility/environment/Makefile
  reproducibility/environment/README.md
  reproducibility/environment/dotenv-gen.sh
  reproducibility/environment/main.tf
  reproducibility/environment/notebooks-instance.tf
  reproducibility/environment/startup-script-gen.sh
  reproducibility/environment/template-post-startup-script.sh
  reproducibility/environment/terraform.tfvars
  reproducibility/environment/variables.tf
  reproducibility/figures/fig2/model1/fig2.py
  reproducibility/figures/fig2/model1/fig2_pancreas_data.py
  reproducibility/figures/fig2/model1/fig2_pbmc_data.py
  reproducibility/figures/fig2/model2/fig2_model2.py
  reproducibility/figures/fig2/model2/fig2_pancreas_data_model2.py
  reproducibility/figures/fig2/model2/fig2_pbmc_data_model2.py
  reproducibility/figures/fig3/fig3.py
  reproducibility/figures/fig3/model1/fig3_allcells_model1.py
  reproducibility/figures/fig3/model1/fig3_uni_bifurcation_model1.py
  reproducibility/figures/fig3/model1/fig3_unipotent_mono_model1.py
  reproducibility/figures/fig3/model1/fig3_unipotent_neu_model1.py
  reproducibility/figures/fig3/model2/fig3_allcells_model2.py
  reproducibility/figures/fig3/model2/fig3_uni_bifurcation_model2.py
  reproducibility/figures/fig3/model2/fig3_unipotent_mono_model2.py
  reproducibility/figures/fig3/model2/fig3_unipotent_neu_model2.py
  reproducibility/figures/readme_figure8.py
  reproducibility/figures/suppfig1_model1_graph.py
  reproducibility/figures/suppfig2.py
  reproducibility/figures/suppfig4_larry_cytotrace.py
  reproducibility/figures/suppfig5.py
  reproducibility/figures/suppfig67_time_evolvedtraj.py
  reproducibility/figures/supptables.py
Labels: enhancement

#20 Cleanup root directory
  .editorconfig
  .github/ISSUE_TEMPLATE.md
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  .travis.yml
  AUTHORS.rst
  CONTRIBUTING.rst
  HISTORY.rst
  MANIFEST.in
  README.md
  README.rst
  conda/conda.recipe/meta.yaml
  conda/environment-cpu.yml
  conda/environment-gpu.yml
  conda/virtual-packages.yml
  docs/authors.md
  docs/contributing.md
  docs/history.md
  docs/index.md
  reproducibility/environment/README.md
  requirements_dev.txt
  setup.py
  tox.ini
Labels: documentation, enhancement

#24 update type annotations based on calls from `fig2_pancreas_data.py`
  .gitignore
  conda/README.md
  noxfile.py
  pyrovelocity/_trainer.py
  pyrovelocity/_velocity.py
  pyrovelocity/_velocity_model.py
  pyrovelocity/_velocity_module.py
  pyrovelocity/api.py
  pyrovelocity/cytotrace.py
  pyrovelocity/data.py
  pyrovelocity/plot.py
  pyrovelocity/utils.py
Labels: enhancement, refactoring

#28 document reproducibility input/output for v0.1.0
  README.md
  conda/conda.recipe/meta.yaml
  conda/recipe/meta.yaml
  pyrovelocity/data.py
  pyrovelocity/plot.py
  reproducibility/environment/startup-script-gen.sh
  reproducibility/figures/README.md
  reproducibility/figures/fig2/README.md
  reproducibility/figures/fig2/fig2.py
  reproducibility/figures/fig2/fig2_pancreas_data.py
  reproducibility/figures/fig2/fig2_pbmc_data.py
  reproducibility/figures/fig3/README.md
  reproducibility/figures/fig3/fig3.py
  reproducibility/figures/fig3/fig3_allcells_cospar.py
  reproducibility/figures/fig3/fig3_allcells_cytotrace.py
  reproducibility/figures/fig3/fig3_allcells_model2.py
  reproducibility/figures/fig3/fig3_uni_bifurcation_model2.py
  reproducibility/figures/fig3/fig3_unipotent_mono_model1.py
  reproducibility/figures/fig3/fig3_unipotent_neu_model1.py
  reproducibility/figures/find_data_read_write.sh
  reproducibility/figures/reproducibility-output-archive.txt
  reproducibility/figures/run_profile_summary.sh
  reproducibility/figures/run_reproducibility.sh
  reproducibility/figures/suppfig1/README.md
  reproducibility/figures/suppfig1/suppfig1_models_graph.py
  reproducibility/figures/suppfig2/README.md
  reproducibility/figures/suppfig3/README.md
  reproducibility/figures/suppfig3/fig2_model2.py
  reproducibility/figures/suppfig3/fig2_pancreas_data_model2.py
  reproducibility/figures/suppfig3/fig2_pbmc_data_model2.py
  reproducibility/figures/suppfig4/suppfig4_larry_cytotrace.py
Labels: documentation, performance, refactoring

#30 add tests to validate module load
  .github/workflows/release.yml
  .github/workflows/tests.yml
  noxfile.py
  pyrovelocity/__init__.py
  setup.cfg
  setup.py
  tests/test_api.py
  tests/test_cytotrace.py
  tests/test_data.py
  tests/test_plot.py
  tests/test_pyrovelocity.py
  tests/test_trainer.py
  tests/test_utils.py
  tests/test_velocity.py
  tests/test_velocity_guide.py
  tests/test_velocity_model.py
  tests/test_velocity_module.py
Labels: ci, github_actions, testing

#31 Suppfig5
  README.md
  pyrovelocity/plot.py
  reproducibility/figures/fig3/fig3.py
  reproducibility/figures/fig3/fig3_allcells_model2.py
  reproducibility/figures/fig3/fig3_uni_bifurcation_model2.py
  reproducibility/figures/fig3/fig3_unipotent_mono_model1.py
  reproducibility/figures/suppfig5/model1/fig3_allcells_model1.py
  reproducibility/figures/suppfig5/model1/fig3_uni_bifurcation_model1.py
  reproducibility/figures/suppfig5/model2/fig3_unipotent_mono_model2.py
  reproducibility/figures/suppfig5/model2/fig3_unipotent_neu_model2.py
  reproducibility/figures/suppfig5/suppfig5.py
  reproducibility/figures/supptables/supptables.py
Labels: documentation

#34 update build process
  README.md
  poetry.lock
  pyproject.toml
  pyrovelocity/plot.py
  reproducibility/figures/fig3/fig3.py
  reproducibility/figures/fig3/fig3_uni_bifurcation_model2.py
  reproducibility/figures/suppfig5/model1/fig3_allcells_model1.py
  reproducibility/figures/suppfig5/model1/fig3_uni_bifurcation_model1.py
  reproducibility/figures/suppfig5/model2/fig3_unipotent_mono_model2.py
  reproducibility/figures/suppfig5/model2/fig3_unipotent_neu_model2.py
  reproducibility/figures/suppfig5/suppfig5.py
  setup.py
Labels: documentation, build

#36 Anaconda and Bioconda with poetry
  conda/recipe/meta.yaml
  docs/source/notebooks/larry.ipynb
  pyproject.toml
Labels: build

#41 add configuration, data version control, and reproducibility pipelines
  .dvc/.gitignore
  .dvc/config
  .dvcignore
  poetry.lock
  pyproject.toml
  pyrovelocity/config.py
  pyrovelocity/data.py
  pyrovelocity/plot.py
  pyrovelocity/utils.py
  reproducibility/environment/.terraform.lock.hcl
  reproducibility/environment/Makefile
  reproducibility/environment/template-post-startup-script.sh
  reproducibility/environment/terraform.tfvars
  reproducibility/figures/.gitignore
  reproducibility/figures/README.md
  reproducibility/figures/archive/find_data_read_write.sh
  reproducibility/figures/archive/reproducibility-output-archive.txt
  reproducibility/figures/archive/run_profile_summary.sh
  reproducibility/figures/archive/run_reproducibility.sh
  reproducibility/figures/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/data/external/.gitignore
  reproducibility/figures/data/processed/.gitignore
  reproducibility/figures/data_download.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig2/fig2_pancreas_data.py
  reproducibility/figures/fig2/fig2_pancreas_plot.py
  reproducibility/figures/fig2/fig2_pancreas_train.py
  reproducibility/figures/fig2/fig2_pbmc_data.py
  reproducibility/figures/fig2/figure.py
  reproducibility/figures/models/pancreas_model1/.gitignore
  reproducibility/figures/models/pbmc68k_model1/.gitignore
  reproducibility/figures/preprocess.py
  reproducibility/figures/reports/fig2/.gitignore
  reproducibility/figures/template-config.yaml
  reproducibility/figures/train.py
  tests/test_config.py
Labels: enhancement
