Repository pinellolab/pyrovelocity, pull requests merged in 2022-10, with the labels that each got.

#5 convert documentation from rST to MyST
  README.md
  docs/_static/logo.png
  docs/_static/pyrovelocity-internal-dependencies.png
  docs/api/api.md
  docs/api/cytotrace.md
  docs/api/data.md
  docs/api/index.md
  docs/api/plot.md
  docs/api/pyrovelocity.md
  docs/api/utils.md
  docs/authors.md
  docs/conf.py
  docs/contributing.md
  docs/history.md
  docs/index.md
  docs/index.rst
  docs/installation.md
  docs/installation.rst
  docs/modules.rst
  docs/pyrovelocity.rst
  docs/readme.md
  docs/readme.rst
  docs/requirements.txt
  docs/source/notebooks/larry.ipynb
  docs/source/notebooks/pancreas.ipynb
  docs/source/notebooks/pbmc.ipynb
  docs/tutorials.md
  docs/usage.md
  docs/usage.rst
Labels: bug, documentation

#7 add bioconda package recipe; improve installation in document
  README.md
  conda.recipe/meta.yaml
  docs/installation.md
Labels: documentation

#13 add poetry dependency management system
  .gitignore
  conda/README.md
  poetry.lock
  pyproject.toml
  pyrovelocity/pyrovelocity.py
Labels: enhancement

#15 add pre-commit and github action for testing
  .darglint
  .flake8
  .github/ISSUE_TEMPLATE.md
  .github/workflows/constraints.txt
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  .travis.yml
  README.md
  README.rst
  conda.recipe/meta.yaml
  conda/README.md
  conda/environment-cpu.yml
  conda/environment-gpu.yml
  conda/gen-conda-lock.sh
  conda/virtual-packages.yml
  docs/conf.py
  docs/index.md
  docs/installation.md
  docs/source/reproducibility/fig2.py
  docs/source/reproducibility/fig2_model2.py
  docs/source/reproducibility/fig2_pancreas_data.py
  docs/source/reproducibility/fig2_pancreas_data_model2.py
  docs/source/reproducibility/fig2_pbmc_data.py
  docs/source/reproducibility/fig2_pbmc_data_model2.py
  docs/source/reproducibility/fig3.py
  docs/source/reproducibility/fig3_allcells_model1.py
  docs/source/reproducibility/fig3_allcells_model2.py
  docs/source/reproducibility/fig3_uni_bifurcation_model1.py
  docs/source/reproducibility/fig3_uni_bifurcation_model2.py
  docs/source/reproducibility/fig3_unipotent_mono_model1.py
  docs/source/reproducibility/fig3_unipotent_mono_model2.py
  docs/source/reproducibility/fig3_unipotent_neu_model1.py
  docs/source/reproducibility/fig3_unipotent_neu_model2.py
  docs/source/reproducibility/readme_figure8.py
  docs/source/reproducibility/suppfig1_model1_graph.py
  docs/source/reproducibility/suppfig2.py
  docs/source/reproducibility/suppfig4_larry_cytotrace.py
  docs/source/reproducibility/suppfig5.py
  docs/source/reproducibility/suppfig67_time_evolvedtraj.py
  docs/source/reproducibility/supptables.py
  noxfile.py
  poetry.lock
  pyproject.toml
  pyrovelocity/__init__.py
  pyrovelocity/_trainer.py
  pyrovelocity/_velocity.py
  pyrovelocity/_velocity_guide.py
  pyrovelocity/_velocity_model.py
  pyrovelocity/_velocity_module.py
  pyrovelocity/api.py
  pyrovelocity/cytotrace.py
  pyrovelocity/data.py
  pyrovelocity/plot.py
  pyrovelocity/utils.py
  requirements_dev.txt
  setup.py
Labels: enhancement

#16 update reproducibility scripts
  docs/source/reproducibility/fig2/model1/fig2.py
  docs/source/reproducibility/fig2/model1/fig2_pancreas_data.py
  docs/source/reproducibility/fig2/model1/fig2_pbmc_data.py
  docs/source/reproducibility/fig2/model2/fig2_model2.py
  docs/source/reproducibility/fig2/model2/fig2_pancreas_data_model2.py
  docs/source/reproducibility/fig2/model2/fig2_pbmc_data_model2.py
  docs/source/reproducibility/fig2_pbmc_data.py
  docs/source/reproducibility/fig2_pbmc_data_model2.py
  docs/source/reproducibility/fig3/fig3.py
  docs/source/reproducibility/fig3/model1/fig3_allcells_model1.py
  docs/source/reproducibility/fig3/model1/fig3_uni_bifurcation_model1.py
  docs/source/reproducibility/fig3/model1/fig3_unipotent_mono_model1.py
  docs/source/reproducibility/fig3/model1/fig3_unipotent_neu_model1.py
  docs/source/reproducibility/fig3/model2/fig3_allcells_model2.py
  docs/source/reproducibility/fig3/model2/fig3_uni_bifurcation_model2.py
  docs/source/reproducibility/fig3/model2/fig3_unipotent_mono_model2.py
  docs/source/reproducibility/fig3/model2/fig3_unipotent_neu_model2.py
  docs/source/reproducibility/readme_figure8.py
  docs/source/reproducibility/suppfig1_model1_graph.py
  docs/source/reproducibility/suppfig2.py
  docs/source/reproducibility/suppfig4_larry_cytotrace.py
  docs/source/reproducibility/suppfig5.py
  docs/source/reproducibility/suppfig67_time_evolvedtraj.py
  docs/source/reproducibility/supptables.py
Labels: bug
