Repository pinellolab/pyrovelocity, pull requests merged in 2023-06, with the labels that each got.

#333 data set prediction from inferred time
  pyrovelocity/config.py
  pyrovelocity/plot.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig3/figure.py
  reproducibility/figures/figS2/figure.py
  reproducibility/figures/figS4/figure.py
  reproducibility/figures/reports/figS2/.gitignore
  reproducibility/figures/reports/figS4/.gitignore
  reproducibility/figures/run_repro.sh
  reproducibility/figures/suppfig4/figure.py
Labels: enhancement

#335 compare PCA and UMAP Rayleigh on minimal gene set projection
  pyrovelocity/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/figS2/figure.py
  reproducibility/figures/figS2/figure_extras.py
Labels: question, performance

#336 add comparison of angle and magnitude uncertainties
  pyrovelocity/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/figS2/figure_extra_2.py
  reproducibility/figures/run.sh
  reproducibility/figures/run_repro.sh
Labels: enhancement

#338 label pbmc10k clusters
  pyrovelocity/config.py
  pyrovelocity/plots/rainbow.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/figS2/figure.py
  reproducibility/figures/label_data.py
  reproducibility/figures/models/pbmc10k_model2/metrics.json
  reproducibility/figures/models/pbmc10k_model2/run_info.json
Labels: enhancement

#341 compute shared time-distance correlation
  pyrovelocity/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/figS2/figure.py
  scripts/data/label_data.py
  scripts/data/label_data_environment.yml
  scripts/git/update-filter-branches.sh
  scripts/metrics/distance_time_correlation_benchmark.py
  tests/test_utils.py
Labels: enhancement

#344 add bone marrow data set
  pyrovelocity/config.py
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/models/bonemarrow_model2/.gitignore
  reproducibility/figures/models/bonemarrow_model2/metrics.json
  reproducibility/figures/models/bonemarrow_model2/run_info.json
  reproducibility/figures/reports/bonemarrow_model2/.gitignore
Labels: enhancement

#348 use predictive with one time point and 30 posterior samples from the …
  Makefile
  pyrovelocity/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/summarize.py
Labels: enhancement

#359 add shared time markers to phase portraits
  pyrovelocity/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/summarize.py
Labels: enhancement

#365 updates for compatibility with cml 0.19.1
  .github/workflows/cml.yml
  dockerfiles/Dockerfile
  reproducibility/figures/upload_figures_drive.sh
Labels: dependencies
