Repository pinellolab/pyrovelocity, pull requests merged in 2023-02, with the labels that each got.

#52 write training/run data to json
  CODE_OF_CONDUCT.md
  pyrovelocity/_trainer.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/pancreas_model1/metrics.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/template-config.yaml
  reproducibility/figures/train.py
Labels: enhancement

#54 add marker comparison across models
  .pre-commit-config.yaml
  pyrovelocity/plot.py
  reproducibility/figures/README.md
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig2/figure.py
  reproducibility/figures/models/pancreas_model1/metrics.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model1/metrics.json
  reproducibility/figures/models/pbmc68k_model1/run_info.json
  reproducibility/figures/models/pbmc68k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
  reproducibility/figures/template-config.yaml
Labels: enhancement, question

#61 add continuous integration for modeling experiments
  .github/pipeline.sh
  .github/workflows/cml.yml
  .pre-commit-config.yaml
  .pre-commit-local.yaml
  README.md
  noxfile.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/pancreas_model1/metrics.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model1/metrics.json
  reproducibility/figures/models/pbmc68k_model1/run_info.json
  reproducibility/figures/models/pbmc68k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
Labels: enhancement, ci

#63 release `v0.1.1`
  .readthedocs.yml
  pyproject.toml
Labels: build
