Repository pinellolab/pyrovelocity, pull requests merged in 2023-04, with the labels that each got.

#96 add dashboard review application
  .darglint
  .flake8
  Makefile
  app/app.py
  app/environment.yml
  dockerfiles/Dockerfile.app
  pyrovelocity/__init__.py
Labels: enhancement

#100 add manual gene or cell selection
  .streamlit/config.toml
  Makefile
  app/app.py
  app/environment.yml
  app/modules/home.py
  app/modules/pancreas.py
  app/modules/simulation.py
  app/modules/simulation/datareview.py
  app/modules/simulation/velocityestimation.py
  app/utils/altair_theme.py
  app/utils/data.py
  app/utils/html_factory.py
  dockerfiles/Dockerfile.app
  poetry.lock
  pyproject.toml
  pyrovelocity/config.py
  reproducibility/figures/config.py
Labels: enhancement

#104 refactor velocity model
  pyrovelocity/_velocity_model.py
  pyrovelocity/_velocity_module.py
  pyrovelocity/utils.py
Labels: refactoring

#105 Upgrade packages with few pinned versions
  conda/environment-gpu-upd.yml
  pyrovelocity/__init__.py
  pyrovelocity/_trainer.py
  pyrovelocity/_velocity.py
  pyrovelocity/_velocity_model.py
  pyrovelocity/api.py
  pyrovelocity/cytotrace.py
  pyrovelocity/data.py
  reproducibility/figures/README.md
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/pancreas_model1/metrics.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/train.py
Labels: dependencies

#106 upgrade package dependencies
  .github/install-pyenv.sh
  .github/pipeline.sh
  .github/workflows/cml.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  .pre-commit-local.yaml
  .readthedocs.yml
  app/modules/simulation/datareview.py
  app/utils/altair_theme.py
  app/utils/data.py
  dockerfiles/Dockerfile
  noxfile.py
  poetry.lock
  pyproject.toml
  pyrovelocity/__init__.py
  pyrovelocity/cytotrace.py
  pyrovelocity/data.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/pancreas_model1/metrics.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model1/metrics.json
  reproducibility/figures/models/pbmc68k_model1/run_info.json
  reproducibility/figures/models/pbmc68k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
  reproducibility/figures/models/pons_model1/metrics.json
  reproducibility/figures/models/pons_model1/run_info.json
  reproducibility/figures/models/pons_model2/metrics.json
  reproducibility/figures/models/pons_model2/run_info.json
Labels: dependencies

#109 automate upgrade notifications
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
Labels: dependencies

#136 update docs to reflect environment upgrade
  .github/SECURITY.md
  README.md
  conda/dep-environment-gpu.yml
  conda/environment-gpu-upd.yml
  conda/environment-gpu.yml
  docs/history.md
  poetry.lock
  pyproject.toml
Labels: documentation

#146 add simulated data for app testing
  .github/workflows/tests.yml
  README.md
  conda/environment-gpu.yml
  docs/api/developer.md
  docs/api/developer/trainer.md
  docs/api/developer/velocity.md
  docs/api/developer/velocity_model.md
  docs/api/developer/velocity_module.md
  docs/api/index.md
  docs/api/user.md
  docs/api/user/api.md
  docs/api/user/cytotrace.md
  docs/api/user/data.md
  docs/api/user/plot.md
  docs/api/user/utils.md
  docs/authors.md
  docs/conf.py
  docs/contributing.md
  docs/index.md
  docs/installation.md
  docs/usage.md
  pyrovelocity/_velocity.py
  pyrovelocity/_velocity_module.py
  pyrovelocity/api.py
  pyrovelocity/data.py
  pyrovelocity/utils.py
  tests/test_utils.py
Labels: enhancement

#150 Reduced pkl file
  pyrovelocity/_velocity.py
  pyrovelocity/plot.py
  pyrovelocity/utils.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/summarize.py
  reproducibility/figures/train.py
Labels: refactoring

#152 add updated pipeline lock
  reproducibility/figures/dvc.lock
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
Labels: refactoring

#160 complete reduction of posterior samples file caches
  README.md
  noxfile.py
  poetry.lock
  pyproject.toml
  pyrovelocity/_velocity.py
  pyrovelocity/api.py
  pyrovelocity/plot.py
  pyrovelocity/utils.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig2/fig2_pancreas_plot.py
  reproducibility/figures/fig2/figure.py
  reproducibility/figures/figS3/figure.py
  reproducibility/figures/models/pancreas_model1/metrics.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model1/metrics.json
  reproducibility/figures/models/pbmc68k_model1/run_info.json
  reproducibility/figures/models/pbmc68k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
  reproducibility/figures/models/pons_model1/metrics.json
  reproducibility/figures/models/pons_model1/run_info.json
  reproducibility/figures/models/pons_model2/metrics.json
  reproducibility/figures/models/pons_model2/run_info.json
  reproducibility/figures/summarize.py
  reproducibility/figures/train.py
  tests/test_utils.py
Labels: performance, testing

#163 automate build for colab environment
  .github/workflows/colab.yml
  README.md
  conda/colab/construct.yaml
  docs/source/notebooks/pyrovelocity_colab_template.ipynb
Labels: documentation, dependencies, github_actions

#165 support python 3.9 and 3.10
  .github/workflows/release.yml
  .github/workflows/tests.yml
  README.md
  noxfile.py
  poetry.lock
  pyproject.toml
  reproducibility/environment/template-post-startup-script.sh
Labels: dependencies

#167 release `v0.1.2`
  conda/colab/construct.yaml
  docs/history.md
  docs/source/notebooks/pyrovelocity_colab_template.ipynb
  pyproject.toml
Labels: build

#168 add updated pipeline lock; reduce model 1 pkl output
  pyrovelocity/_velocity.py
  reproducibility/figures/README.md
  reproducibility/figures/dvc.lock
  reproducibility/figures/models/pancreas_model1/metrics.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model1/metrics.json
  reproducibility/figures/models/pbmc68k_model1/run_info.json
  reproducibility/figures/models/pons_model1/metrics.json
  reproducibility/figures/models/pons_model1/run_info.json
Labels: refactoring

#182 add pipeline stage for generating simulated data
  pyrovelocity/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/data_download.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
Labels: testing

#190 add pipeline stages for training simulated data
  pyrovelocity/config.py
  pyrovelocity/data.py
  pyrovelocity/plot.py
  pyrovelocity/utils.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/medium_model1/.gitignore
  reproducibility/figures/models/medium_model1/metrics.json
  reproducibility/figures/models/medium_model1/run_info.json
  reproducibility/figures/models/medium_model2/.gitignore
  reproducibility/figures/models/medium_model2/metrics.json
  reproducibility/figures/models/medium_model2/run_info.json
Labels: testing

#192 add pipeline stages for plotting simulated data
  pyrovelocity/config.py
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/medium_model1/run_info.json
  reproducibility/figures/models/medium_model2/run_info.json
  reproducibility/figures/reports/medium_model1/.gitignore
  reproducibility/figures/reports/medium_model2/.gitignore
Labels: testing

#196 update demo code in README
  README.md
Labels: documentation

#209 add function to estimate criticality index
  pyrovelocity/metrics/criticality_index.py
  tests/metrics/test_criticality_index.py
Labels: enhancement

#214 preprocess and train with LARRY data
  .github/pipeline.sh
  pyrovelocity/config.py
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/larry_model2/.gitignore
  reproducibility/figures/models/larry_model2/metrics.json
  reproducibility/figures/models/larry_model2/run_info.json
Labels: enhancement

#228 automate deployment of review application
  .github/workflows/deploy.yml
Labels: enhancement, ci

#225 train mono / neu / multi subsets of larry
  pyrovelocity/config.py
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/larry_mono_model2/.gitignore
  reproducibility/figures/models/larry_mono_model2/metrics.json
  reproducibility/figures/models/larry_mono_model2/run_info.json
  reproducibility/figures/models/larry_multilineage_model2/.gitignore
  reproducibility/figures/models/larry_multilineage_model2/metrics.json
  reproducibility/figures/models/larry_multilineage_model2/run_info.json
  reproducibility/figures/models/larry_neu_model2/.gitignore
  reproducibility/figures/models/larry_neu_model2/metrics.json
  reproducibility/figures/models/larry_neu_model2/run_info.json
Labels: enhancement

#216 add shared time uncertainty plot to summarize stages
  reproducibility/figures/summarize.py
Labels: enhancement
