Repository pinellolab/pyrovelocity, pull requests merged in 2023-03, with the labels that each got.

#73 add pipeline stages for pons oligodendrocyte data
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/pons_model1/.gitignore
  reproducibility/figures/models/pons_model1/metrics.json
  reproducibility/figures/models/pons_model1/run_info.json
  reproducibility/figures/models/pons_model2/.gitignore
  reproducibility/figures/models/pons_model2/metrics.json
  reproducibility/figures/models/pons_model2/run_info.json
  reproducibility/figures/template-config.yaml
Labels: enhancement

#76 add uncertainty analysis boxplot for the kinetics parameters
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig2/figure.py
  reproducibility/figures/template-config.yaml
Labels: enhancement, python

#82 add citation bib
  .gitignore
  CITATION.bib
  setup.cfg
  setup.py
Labels: documentation

#83 add html callgraph
  poetry.lock
  pyproject.toml
  reproducibility/figures/callgraph.py
Labels: enhancement

#84 add utility to pretty print dictionaries
  poetry.lock
  pyproject.toml
  pyrovelocity/cytotrace.py
  pyrovelocity/data.py
  pyrovelocity/utils.py
Labels: enhancement

#87 add magnitude uncertainty figure
  pyrovelocity/plot.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/fig2/figure.py
  reproducibility/figures/template-config.yaml
Labels: enhancement

#91 produce summary plots package for all data sets
  pyrovelocity/_velocity.py
  pyrovelocity/plot.py
  pyrovelocity/utils.py
  reproducibility/figures/config.yaml
  reproducibility/figures/polar_histogram.py
  reproducibility/figures/preprocess.py
  reproducibility/figures/summarize.py
  reproducibility/figures/template-config.yaml
Labels: enhancement

#92 set preprocessing to macroscopic gene set by default and retrain
  .github/pipeline.sh
  .github/workflows/cml.yml
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig2/fig2_pancreas_plot.py
  reproducibility/figures/models/pancreas_model1/metrics.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model1/metrics.json
  reproducibility/figures/models/pbmc68k_model1/run_info.json
  reproducibility/figures/models/pbmc68k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
  reproducibility/figures/models/pons_model1/metrics.json
  reproducibility/figures/models/pons_model1/run_info.json
  reproducibility/figures/models/pons_model2/metrics.json
  reproducibility/figures/models/pons_model2/run_info.json
  reproducibility/figures/preprocess.py
  reproducibility/figures/summarize.py
  reproducibility/figures/train.py
  reproducibility/figures/zenconfig.py
  reproducibility/figures/zenconfig.yaml
Labels: enhancement

#94 add pipeline stages for data set summary
  .dvcignore
  reproducibility/figures/archive/template-config.yaml
  reproducibility/figures/config.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/reports/pancreas_model1/.gitignore
  reproducibility/figures/reports/pancreas_model2/.gitignore
  reproducibility/figures/reports/pbmc68k_model1/.gitignore
  reproducibility/figures/reports/pbmc68k_model2/.gitignore
  reproducibility/figures/reports/pons_model1/.gitignore
  reproducibility/figures/reports/pons_model2/.gitignore
  reproducibility/figures/summarize.py
  reproducibility/figures/zenconfig.py
  reproducibility/figures/zenconfig.yaml
Labels: enhancement
