Repository pinellolab/pyrovelocity, pull requests merged in 2023-05, with the labels that each got.

#232 add figures for shared time uncertainty
  pyrovelocity/_velocity.py
  reproducibility/figures/README.md
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig2/figure_extras.py
  reproducibility/figures/summarize.py
Labels: documentation

#236 plot angle uncertainty metrics
  reproducibility/figures/dvc.lock
  reproducibility/figures/fig2/figure_extras.py
Labels: documentation

#241 preprocess and train model on pbmc10k
  pyrovelocity/config.py
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/pbmc10k_model2/.gitignore
  reproducibility/figures/models/pbmc10k_model2/metrics.json
  reproducibility/figures/models/pbmc10k_model2/run_info.json
Labels: enhancement

#244 update pbmc10k data set download
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
Labels: bug

#249 add magnitude and pca space uncertainties evaluation
  pyrovelocity/_velocity.py
  pyrovelocity/plot.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/models/larry_model2/metrics.json
  reproducibility/figures/models/larry_model2/run_info.json
  reproducibility/figures/models/larry_mono_model2/metrics.json
  reproducibility/figures/models/larry_mono_model2/run_info.json
  reproducibility/figures/models/larry_multilineage_model2/metrics.json
  reproducibility/figures/models/larry_multilineage_model2/run_info.json
  reproducibility/figures/models/larry_neu_model2/metrics.json
  reproducibility/figures/models/larry_neu_model2/run_info.json
  reproducibility/figures/models/medium_model1/metrics.json
  reproducibility/figures/models/medium_model1/run_info.json
  reproducibility/figures/models/medium_model2/metrics.json
  reproducibility/figures/models/medium_model2/run_info.json
  reproducibility/figures/models/pancreas_model1/run_info.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc10k_model2/metrics.json
  reproducibility/figures/models/pbmc10k_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model1/metrics.json
  reproducibility/figures/models/pbmc68k_model1/run_info.json
  reproducibility/figures/models/pbmc68k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
  reproducibility/figures/models/pons_model1/metrics.json
  reproducibility/figures/models/pons_model1/run_info.json
  reproducibility/figures/models/pons_model2/metrics.json
  reproducibility/figures/models/pons_model2/run_info.json
  reproducibility/figures/run.sh
  reproducibility/figures/summarize.py
Labels: enhancement

#251 add differentiated larry
  pyrovelocity/config.py
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig2/figure_extras.py
  reproducibility/figures/models/larry_mono_model2/metrics.json
  reproducibility/figures/models/larry_mono_model2/run_info.json
  reproducibility/figures/models/larry_multilineage_model2/metrics.json
  reproducibility/figures/models/larry_multilineage_model2/run_info.json
  reproducibility/figures/models/larry_neu_model2/metrics.json
  reproducibility/figures/models/larry_neu_model2/run_info.json
  reproducibility/figures/models/larry_tips_model2/.gitignore
  reproducibility/figures/models/larry_tips_model2/metrics.json
  reproducibility/figures/models/larry_tips_model2/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc10k_model2/metrics.json
  reproducibility/figures/models/pbmc10k_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
  reproducibility/figures/reports/larry_tips_model2/.gitignore
  reproducibility/figures/train.py
Labels: enhancement

#253 update embedding space comparison
  reproducibility/figures/dvc.lock
  reproducibility/figures/fig2/figure_extras.py
Labels: enhancement

#259 Reproduce on all Larry-related datasets and generate figureS3_extra
  pyrovelocity/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/figS3/figure_extras.py
  reproducibility/figures/models/larry_model2/metrics.json
  reproducibility/figures/models/larry_model2/run_info.json
  reproducibility/figures/models/larry_mono_model2/run_info.json
  reproducibility/figures/models/larry_multilineage_model2/run_info.json
  reproducibility/figures/models/larry_neu_model2/run_info.json
  reproducibility/figures/models/larry_tips_model2/run_info.json
Labels: enhancement

#262 build gpu-specific docker image
  .github/workflows/cml.yml
  .github/workflows/colab.yml
  .github/workflows/docker.yml
  .pre-commit-config.yaml
  README.md
  conda/colab/construct.yaml
  dockerfiles/Dockerfile.conda
  dockerfiles/Dockerfile.conda.cpu
Labels: enhancement, ci

#264 add draft for distributed pipeline
  .github/workflows/cml.yml
  poetry.lock
  pyproject.toml
  reproducibility/pipelines/argo/.envrc.example
  reproducibility/pipelines/argo/.gitignore
  reproducibility/pipelines/argo/__init__.py
  reproducibility/pipelines/argo/components/environment_log_component.py
  reproducibility/pipelines/argo/construct_pipeline.py
  reproducibility/pipelines/argo/run_pipeline.py
Labels: enhancement

#267 add single-node pipeline test sandbox
  pyrovelocity/config.py
  reproducibility/test/.gitignore
  reproducibility/test/config.py
  reproducibility/test/config.yaml
  reproducibility/test/data/processed/.gitignore
  reproducibility/test/data_download.py
  reproducibility/test/dvc.lock
  reproducibility/test/dvc.yaml
  reproducibility/test/models/medium_model2/.gitignore
  reproducibility/test/models/medium_model2/metrics.json
  reproducibility/test/models/medium_model2/run_info.json
  reproducibility/test/preprocess.py
  reproducibility/test/reports/medium_model2/.gitignore
  reproducibility/test/summarize.py
  reproducibility/test/train.py
Labels: testing

#275 update minimal count threshold filtration preprocessing
  .github/pipeline.sh
  pyrovelocity/data.py
  pyrovelocity/utils.py
  reproducibility/figures/data/processed/.gitignore
  reproducibility/figures/dvc.lock
Labels: enhancement

#278 add hypersphere distribution divergence
  pyrovelocity/metrics/hypersphere_distribution_divergence.py
Labels: enhancement

#280 add pipeline stages for larry auxiliary data
  conda/environment-cpu.yml
  conda/environment-gpu.yml
  pyrovelocity/config.py
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
Labels: enhancement

#282 add violin plots for uncertainty measurements
  pyrovelocity/config.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/figS3/figure_extras.py
Labels: enhancement

#283 update data filter pipeline
  .github/pipeline.sh
  pyrovelocity/config.py
  pyrovelocity/data.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/models/pons_model2/metrics.json
  reproducibility/figures/models/pons_model2/run_info.json
Labels: enhancement

#285 fix redundancy in pbmc68k preprocessing
  .github/pipeline.sh
  pyrovelocity/data.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/models/larry_mono_model2/metrics.json
  reproducibility/figures/models/larry_multilineage_model2/metrics.json
  reproducibility/figures/models/larry_neu_model2/metrics.json
  reproducibility/figures/models/larry_tips_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pbmc10k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
  reproducibility/figures/models/simulate_medium_model2/metrics.json
Labels: enhancement

#288 fix duplicate pca call
  .github/pipeline.sh
  pyrovelocity/plot.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/models/pbmc68k_model2/metrics.json
Labels: enhancement

#289 update figure summary
  pyrovelocity/config.py
  pyrovelocity/plot.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig2/figure.py
  reproducibility/figures/reports/larry_model2/.gitignore
  reproducibility/figures/summarize.py
  reproducibility/figures/suppfig1/suppfig1_models_graph.py
Labels: enhancement

#296 add script to upload run data to drive
  pyrovelocity/plot.py
  reproducibility/figures/dvc.lock
  reproducibility/figures/summarize.py
  reproducibility/figures/upload_figures_drive.sh
Labels: enhancement

#298 add cluster-conditional distribution plots
  pyrovelocity/config.py
  pyrovelocity/plot.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/reports/larry_tips_model2/.gitignore
  reproducibility/figures/reports/pbmc10k_model2/.gitignore
  reproducibility/figures/summarize.py
Labels: enhancement

#301 update figure 3
  pyrovelocity/plot.py
  reproducibility/figures/config.yaml
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/fig3/figure.py
  reproducibility/figures/summarize.py
Labels: enhancement

#303 enable rclone in ci
  .github/pipeline.sh
  .github/workflows/cml.yml
  README.md
  reproducibility/figures/dvc.lock
  reproducibility/figures/figS3/figure_extras.py
  reproducibility/figures/reports/larry_model2/.gitignore
  reproducibility/figures/reports/larry_tips_model2/.gitignore
  reproducibility/figures/reports/pbmc10k_model2/.gitignore
  reproducibility/figures/summarize.py
  reproducibility/figures/upload_figures_drive.sh
Labels: enhancement, ci

#305 add parameterized count threshold
  pyrovelocity/config.py
  pyrovelocity/data.py
  pyrovelocity/plot.py
  pyrovelocity/utils.py
  reproducibility/figures/config.yaml
  reproducibility/figures/data/processed/.gitignore
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/models/larry_model2/metrics.json
  reproducibility/figures/models/larry_model2/run_info.json
  reproducibility/figures/models/larry_mono_model2/metrics.json
  reproducibility/figures/models/larry_mono_model2/run_info.json
  reproducibility/figures/models/larry_multilineage_model2/metrics.json
  reproducibility/figures/models/larry_multilineage_model2/run_info.json
  reproducibility/figures/models/larry_neu_model2/metrics.json
  reproducibility/figures/models/larry_neu_model2/run_info.json
  reproducibility/figures/models/larry_tips_model2/metrics.json
  reproducibility/figures/models/larry_tips_model2/run_info.json
  reproducibility/figures/models/pancreas_model2/metrics.json
  reproducibility/figures/models/pancreas_model2/run_info.json
  reproducibility/figures/models/pbmc10k_model2/metrics.json
  reproducibility/figures/models/pbmc10k_model2/run_info.json
  reproducibility/figures/models/pbmc68k_model2/metrics.json
  reproducibility/figures/models/pbmc68k_model2/run_info.json
  reproducibility/figures/models/pons_model2/metrics.json
  reproducibility/figures/models/pons_model2/run_info.json
  reproducibility/figures/models/simulate_medium_model2/metrics.json
  reproducibility/figures/models/simulate_medium_model2/run_info.json
  reproducibility/figures/preprocess.py
Labels: enhancement

#312 integrate gene selection with parameter distribution estimates
  .github/workflows/cml.yml
  pyrovelocity/plot.py
  pyrovelocity/plots/rainbow.py
  reproducibility/figures/.gitignore
  reproducibility/figures/dvc.lock
  reproducibility/figures/dvc.yaml
  reproducibility/figures/summarize.py
Labels: enhancement

#327 update pipeline ci timeout
  .github/pipeline.sh
  .github/workflows/cml.yml
Labels: ci

#329 add config yaml to drive output
  reproducibility/figures/upload_figures_drive.sh
Labels: ci
